theme: jekyll-theme-minimal
title: The Metamorphosis of Movie Archetypes: A timeless tale of film personas
description: A template website for ADA
show_downloads: True
navigation:
  - title: Introduction
    url: /
  - title: Example
    url: example
